language: java
jdk: 
- openjdk8 
script: ant build

addons:
  sonarcloud:
    organization: meghanatran100
    token: travis encrypt asdhjrlakjetwoihe39204iejhkawek
script:
- ant build
- sonar-scanner
